services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
        NEXT_PUBLIC_ATTENDANCE_TARGET_LATITUDE: ${NEXT_PUBLIC_ATTENDANCE_TARGET_LATITUDE}
        NEXT_PUBLIC_ATTENDANCE_TARGET_LONGITUDE: ${NEXT_PUBLIC_ATTENDANCE_TARGET_LONGITUDE}
        NEXT_PUBLIC_ATTENDANCE_TARGET_RADIUS_METERS: ${NEXT_PUBLIC_ATTENDANCE_TARGET_RADIUS_METERS}
        NEXT_PUBLIC_ATTENDANCE_TARGET_LABEL: ${NEXT_PUBLIC_ATTENDANCE_TARGET_LABEL}
    container_name: frontend-prod
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
