FROM node:22-alpine AS deps

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci


FROM node:22-alpine AS builder

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL

ARG NEXT_PUBLIC_DEPLOY_TARGET
ENV NEXT_PUBLIC_DEPLOY_TARGET=$NEXT_PUBLIC_DEPLOY_TARGET

ARG NEXT_PUBLIC_ATTENDANCE_TARGET_LATITUDE
ENV NEXT_PUBLIC_ATTENDANCE_TARGET_LATITUDE=$NEXT_PUBLIC_ATTENDANCE_TARGET_LATITUDE

ARG NEXT_PUBLIC_ATTENDANCE_TARGET_LONGITUDE
ENV NEXT_PUBLIC_ATTENDANCE_TARGET_LONGITUDE=$NEXT_PUBLIC_ATTENDANCE_TARGET_LONGITUDE

ARG NEXT_PUBLIC_ATTENDANCE_TARGET_RADIUS_METERS
ENV NEXT_PUBLIC_ATTENDANCE_TARGET_RADIUS_METERS=$NEXT_PUBLIC_ATTENDANCE_TARGET_RADIUS_METERS

ARG NEXT_PUBLIC_ATTENDANCE_TARGET_LABEL
ENV NEXT_PUBLIC_ATTENDANCE_TARGET_LABEL=$NEXT_PUBLIC_ATTENDANCE_TARGET_LABEL

ARG NEXT_PUBLIC_GOOGLE_APPS_SCRIPT_FILE_API_URL
ENV NEXT_PUBLIC_GOOGLE_APPS_SCRIPT_FILE_API_URL=$NEXT_PUBLIC_GOOGLE_APPS_SCRIPT_FILE_API_URL

RUN npm run build


FROM node:22-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/.next/standalone ./

EXPOSE 3000

CMD ["node", "server.js"]